# E-commerce Customer Intelligence
## Data Preparation and Cleaning

### Objective
Prepare the dataset for customer analysis, segmentation, and predictive modeling by cleaning missing values, fixing data types, checking duplicates, and understanding the basic structure of the data.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import sklearn

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
print("Setup completee")

Setup completee

In [3]:
import pandas as pd

customers = pd.read_csv("../data/olist_customers_dataset.csv")
orders = pd.read_csv("../data/olist_orders_dataset.csv")
order_items = pd.read_csv("../data/olist_order_items_dataset.csv")
payments = pd.read_csv("../data/olist_order_payments_dataset.csv")
reviews = pd.read_csv("../data/olist_order_reviews_dataset.csv")
products = pd.read_csv("../data/olist_products_dataset.csv")
sellers = pd.read_csv("../data/olist_sellers_dataset.csv")
category_translation = pd.read_csv("../data/product_category_name_translation.csv")

print("loaded")
print("customers:", customers.shape)
print("orders:", orders.shape)
print("order_items:", order_items.shape)
print("payments:", payments.shape)
print("reviews:", reviews.shape)
print("products:", products.shape)
print("sellers:", sellers.shape)
print("category_translation:", category_translation.shape)

loaded
customers: (99441, 5)
orders: (99441, 8)
order_items: (112650, 7)
payments: (103886, 5)
reviews: (99224, 7)
products: (32951, 9)
sellers: (3095, 4)
category_translation: (71, 2)

In [4]:
print("orders")
print(orders.columns.tolist())
print()

print("order_items")
print(order_items.columns.tolist())
print()

print("payments")
print(payments.columns.tolist())
print()

print("reviews")
print(reviews.columns.tolist())
print()

print("customers")
print(customers.columns.tolist())
print()

print("productss")
print(products.columns.tolist())
print()

print("sellers")
print(sellers.columns.tolist())

orders
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

order_items
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

payments
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

reviews
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

customers
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

productss
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

sellers
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

In [6]:
master_df = orders.merge(customers, on="customer_id", how="left") \
                  .merge(order_items, on="order_id", how="left") \
                  .merge(payments, on="order_id", how="left") \
                  .merge(reviews, on="order_id", how="left") \
                  .merge(products, on="product_id", how="left") \
                  .merge(sellers, on="seller_id", how="left") \
                  .merge(category_translation, on="product_category_name", how="left")

print(master_df.shape)
master_df.head()

(119143, 40)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP,auto

In [7]:
print("Total rows:", len(master_df))
print("Unique orders:", master_df["order_id"].nunique())
print("Duplicate rows:", master_df.duplicated().sum())

Total rows: 119143
Unique orders: 99441
Duplicate rows: 0

In [9]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   customer_unique_id             119143 non-null  object
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  object
 11  customer_state                 119143 non-null  object
 12  order_item_id                  118310 non-null  float64
 13  product_id                     118310 non-null  object
 14  seller_id                      118310 non-null  object
 15  shipping_limit_date            118310 non-null  object
 16  price                          118310 non-null  float64
 17  freight_value                  118310 non-null  float64
 18  payment_sequential             119140 non-null  float64
 19  payment_type                   119140 non-null  object
 20  payment_installments           119140 non-null  float64
 21  payment_value                  119140 non-null  float64
 22  review_id                      118146 non-null  object
 23  review_score                   118146 non-null  float64
 24  review_comment_title           13989 non-null   object
 25  review_comment_message         50245 non-null   object
 26  review_creation_date           118146 non-null  object
 27  review_answer_timestamp        118146 non-null  object
 28  product_category_name          116601 non-null  object
 29  product_name_lenght            116601 non-null  float64
 30  product_description_lenght     116601 non-null  float64
 31  product_photos_qty             116601 non-null  float64
 32  product_weight_g               118290 non-null  float64
 33  product_length_cm              118290 non-null  float64
 34  product_height_cm              118290 non-null  float64
 35  product_width_cm               118290 non-null  float64
 36  seller_zip_code_prefix         118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
 39  product_category_name_english  116576 non-null  object
dtypes: float64(15), int64(1), object(24)
memory usage: 36.4+ MB

In [8]:
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'shipping_limit_date',
    'review_creation_date',
    'review_answer_timestamp'
]

for col in date_cols:
    if col in master_df.columns:
        master_df[col] = pd.to_datetime(master_df[col], errors='coerce')

master_df[date_cols].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
shipping_limit_date              datetime64[ns]
review_creation_date             datetime64[ns]
review_answer_timestamp          datetime64[ns]
dtype: object

In [13]:
order_level_df = master_df.groupby('order_id').agg(
    customer_id=('customer_id', 'first'),
    customer_unique_id=('customer_unique_id', 'first'),
    order_status=('order_status', 'first'),
    order_purchase_timestamp=('order_purchase_timestamp', 'first'),
    order_approved_at=('order_approved_at', 'first'),
    order_delivered_carrier_date=('order_delivered_carrier_date', 'first'),
    order_delivered_customer_date=('order_delivered_customer_date', 'first'),
    order_estimated_delivery_date=('order_estimated_delivery_date', 'first'),
    review_creation_date=('review_creation_date', 'first'),
    review_answer_timestamp=('review_answer_timestamp', 'first'),
    customer_city=('customer_city', 'first'),
    customer_state=('customer_state', 'first'),

    order_item_count=('order_item_id', 'nunique'),
    product_count=('product_id', 'nunique'),
    seller_count=('seller_id', 'nunique'),
    category_count=('product_category_name_english', 'nunique'),

    total_price=('price', 'sum'),
    total_freight=('freight_value', 'sum'),
    review_score=('review_score', 'max')
).reset_index()
order_level_df.head()

,order_id,customer_id,customer_unique_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_creation_date,review_answer_timestamp,customer_city,customer_state,order_item_count,product_count,seller_count,category_count,total_price,total_freight,review_score
0,00010242fe8c5a6d1ba2dd792cb16214,3ce436f183e68e07877b285a838db11a,871766c5855e863f6eccc05f988b23cb,delivered,2017-09-13 08:59:02,2017-09-13 09:45:35,2017-09-19 18:34:16,2017-09-20 23:43:48,2017-09-29,2017-09-21,2017-09-22 10:57:03,campos dos goytacazes,RJ,1,1,1,1,58.90,13.29,5.0
1,00018f77f2f0320c557190d7a144bdd3,f6dd3ec061db4e3987629fe6b26e5cce,eb28e67c4c0b83846050ddfb8a35d051,delivered,2017-04-26 10:53:06,2017-04-26 11:05:13,2017-05-04 14:35:00,2017-05-12 16:04:24,2017-05-15,2017-05-13,2017-05-15 11:34:13,santa fe do sul,SP,1,1,1,1,239.90,19.93,4.0
2,000229ec398224ef6ca0657da4fc703e,6489ae5e4333f3693df5ad4372dab6d3,3818d81c6709e39d06b2738a8d3a2474,delivered,2018-01-14 14:33:31,2018-01-14 14:48:30,2018-01-16 12:36:48,2018-01-22 13:19:16,2018-02-05,2018-01-23,2018-01-23 16:06:31,para de minas,MG,1,1,1,1,199.00,17.87,5.0
3,00024acbcdf0a6daa1e931b038114c75,d4eb9395c8c0431ee92fce09860c5a06,af861d436cfc08b2c2ddefd0ba074622,delivered,2018-08-08 10:00:35,2018-08-08 10:10:18,2018-08-10 13:28:00,2018-08-14 13:32:39,2018-08-20,2018-08-15,2018-08-15 16:39:01,atibaia,SP,1,1,1,1,12.99,12.79,4.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,58dbd0b2d70206bf40e62cd34e84d795,64b576fb70d441e8f1b2d7d446e483c5,delivered,2017-02-04 13:57:51,2017-02-04 14:10:13,2017-02-16 09:46:09,2017-03-01 16:42:31,2017-03-17,2017-03-02,2017-03-03 10:54:59,varzea paulista,SP,1,1,1,1,199.90,18.14,5.0

In [14]:
payment_order_df = payments.groupby('order_id', as_index=False).agg(
    total_payment=('payment_value', 'sum'),
    payment_installments=('payment_installments', 'max')
)

order_level_df = order_level_df.merge(payment_order_df, on='order_id', how='left')
payment_order_df.head()

                           order_id  total_payment  payment_installments
0  00010242fe8c5a6d1ba2dd792cb16214          72.19                     2
1  00018f77f2f0320c557190d7a144bdd3         259.83                     3
2  000229ec398224ef6ca0657da4fc703e         216.87                     5
3  00024acbcdf0a6daa1e931b038114c75          25.78                     2
4  00042b26cf59d7ce69dfabb4e55b4fd9         218.04                     3

In [15]:
print("order_level_df shape:", order_level_df.shape)
print("Unique orders:", order_level_df['order_id'].nunique())
print("Duplicate order_id:", order_level_df['order_id'].duplicated().sum())

order_level_df.isnull().sum().sort_values(ascending=False).head(15)

order_level_df shape: (99441, 22)
Unique orders: 99441
Duplicate order_id: 0

order_delivered_customer_date    2965
order_delivered_carrier_date     1783
review_score                      768
review_creation_date              768
review_answer_timestamp           768
order_approved_at                 160
payment_installments                1
total_payment                       1
product_count                       0
total_freight                       0
total_price                         0
category_count                      0
seller_count                        0
order_id                            0
order_item_count                    0
dtype: int64

### feature Engineering

In [16]:
order_level_df['purchase_year'] = order_level_df['order_purchase_timestamp'].dt.year
order_level_df['purchase_month'] = order_level_df['order_purchase_timestamp'].dt.to_period('M').astype(str)
order_level_df['purchase_day'] = order_level_df['order_purchase_timestamp'].dt.day_name()

# order value
order_level_df['order_value'] = order_level_df['total_price'] + order_level_df['total_freight']

# approval delay in days
order_level_df['approval_delay_days'] = (
    order_level_df['order_approved_at'] - order_level_df['order_purchase_timestamp']
).dt.total_seconds() / (24 * 60 * 60)

# delivery time in days
order_level_df['delivery_days'] = (
    order_level_df['order_delivered_customer_date'] - order_level_df['order_purchase_timestamp']
).dt.total_seconds() / (24 * 60 * 60)

# seller-to-customer delivery time after carrier pickup
order_level_df['carrier_to_customer_days'] = (
    order_level_df['order_delivered_customer_date'] - order_level_df['order_delivered_carrier_date']
).dt.total_seconds() / (24 * 60 * 60)

# estimated vs actual delivery gap
order_level_df['delivery_delay_days'] = (
    order_level_df['order_delivered_customer_date'] - order_level_df['order_estimated_delivery_date']
).dt.total_seconds() / (24 * 60 * 60)

# late delivery flag
order_level_df['is_late_delivery'] = np.where(order_level_df['delivery_delay_days'] > 0, 1, 0)

# review buckets
order_level_df['review_bucket'] = pd.cut(
    order_level_df['review_score'],
    bins=[0, 2, 3, 5],
    labels=['Bad', 'Neutral', 'Good'],
    include_lowest=True
)

# order value buckets
order_level_df['order_value_bucket'] = pd.qcut(
    order_level_df['order_value'],
    q=4,
    labels=['Low Value', 'Mid-Low', 'Mid-High', 'High Value'],
    duplicates='drop'
)

In [17]:
order_level_df[['order_value', 'approval_delay_days', 'delivery_days',
                'carrier_to_customer_days', 'delivery_delay_days']].describe()

,order_value,approval_delay_days,delivery_days,carrier_to_customer_days,delivery_delay_days
count,99441.000000,99281.000000,96476.000000,96475.000000,96476.000000
mean,167.372928,0.434129,12.558702,9.330547,-11.179120
std,255.145677,1.084917,9.546530,8.760122,10.186113
min,0.000000,0.000000,0.533414,-16.096169,-146.016123
25%,62.290000,0.008958,6.766403,4.099948,-16.244384
50%,106.970000,0.014306,10.217755,7.099769,-11.948941
75%,182.060000,0.607535,15.720327,12.029115,-6.390000
max,13664.080000,187.882523,209.628611,205.190972,188.975081

In [18]:
order_level_df[['is_late_delivery', 'review_bucket', 'order_value_bucket']].head()

   is_late_delivery review_bucket order_value_bucket
0                 0          Good            Mid-Low
1                 0          Good         High Value
2                 0          Good         High Value
3                 0          Good          Low Value
4                 0          Good         High Value

In [19]:
order_level_df.loc[order_level_df['approval_delay_days'] < 0, 'approval_delay_days'] = np.nan
order_level_df.loc[order_level_df['delivery_days'] < 0, 'delivery_days'] = np.nan
order_level_df.loc[order_level_df['carrier_to_customer_days'] < 0, 'carrier_to_customer_days'] = np.nan

In [20]:
order_level_df[['approval_delay_days', 'delivery_days', 'carrier_to_customer_days', 'delivery_delay_days']].describe()

,approval_delay_days,delivery_days,carrier_to_customer_days,delivery_delay_days
count,99281.000000,96476.000000,96452.000000,96476.000000
mean,0.434129,12.558702,9.333551,-11.179120
std,1.084917,9.546530,8.758825,10.186113
min,0.000000,0.533414,0.000000,-146.016123
25%,0.008958,6.766403,4.101525,-16.244384
50%,0.014306,10.217755,7.100312,-11.948941
75%,0.607535,15.720327,12.030443,-6.390000
max,187.882523,209.628611,205.190972,188.975081

In [21]:
delivered_df = order_level_df[order_level_df['order_status'] == 'delivered'].copy()

print("Delivered orders:", delivered_df.shape)

Delivered orders: (96478, 33)

In [23]:
import os

os.makedirs('outputs', exist_ok=True)

order_level_df.to_csv('outputs/order_level_df.csv', index=False)
delivered_df.to_csv('outputs/delivered_orders_df.csv', index=False)

print("Files saved successfully.")

Files saved successfully.

In [26]:
order_level_df.to_csv('outputs/order_level_df.csv', index=False)
delivered_df.to_csv('outputs/delivered_orders_df.csv', index=False)